import { Card } from '@/components/ui/Card'

const labels = { satisfaction_score: ['Customer Satisfaction', 'Customers with lower satisfaction are more likely to churn.'], avg_monthly_gb_download: ['Monthly Internet Usage', 'Usage patterns help identify customers at risk of disengaging.'], tenure_in_months: ['Time with Company', 'Shorter relationships can signal a higher likelihood of churn.'], monthly_charges: ['Monthly Bill', 'Higher bills can create price sensitivity and increase churn risk.'], monthly_charge: ['Monthly Bill', 'Higher bills can create price sensitivity and increase churn risk.'], contract: ['Contract Type', 'Flexible contracts often need more proactive retention outreach.'] }

export function FeatureImportancePanel({ features = [] }) {
  const maximum = Math.max(...features.map((feature) => Math.abs(Number(feature.impact || 0))), 1)
  return <Card title="Feature importance" subtitle="What is influencing churn risk across recent predictions?">
    <div className="space-y-4">{features.length ? features.slice(0, 5).map((feature, index) => { const [name, explanation] = labels[feature.feature] || [String(feature.feature || 'Customer signal').replaceAll('_', ' '), 'This signal contributes to the model’s retention assessment.']; const impact = Math.abs(Number(feature.impact || 0)); const percentage = Math.max(4, (impact / maximum) * 100); return <div key={`${feature.feature}-${index}`}><div className="flex items-center justify-between gap-3"><div><p className="font-semibold text-slate-900 dark:text-white">{name}</p><p className="mt-0.5 text-xs leading-5 text-slate-500 dark:text-slate-400">{explanation}</p></div><span className="whitespace-nowrap rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700 dark:bg-blue-400/15 dark:text-blue-200">Impact {impact.toFixed(3)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-700"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-violet-500" style={{ width: `${percentage}%` }} /></div></div> }) : <p className="rounded-2xl border border-dashed border-slate-300 p-5 text-sm text-slate-500 dark:border-slate-700">Feature importance will appear after prediction explanations are recorded.</p>}</div>
  </Card>
}
