apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_PASSWORD: "change-me-staging"
  MYSQL_PASSWORD: "change-me-staging"
  MYSQL_ROOT_PASSWORD: "change-me-root-staging"
  JWT_SECRET: "change-me-jwt-staging"
  JWT_REFRESH_SECRET: "change-me-refresh-staging"
